config/routes.rb
Rails.application.routes.draw do
  root 'items#show'
  get 'long', to: "items#long"
  get 'mini', to: "items#mini"
  get 'jeans', to: "items#jeans"
  get 'dress', to: "items#dress"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def show
    end

    def long
        response = RakutenWebService::Ichiba::Item.search(keyword: "スカート ロング", imageFlag: 1)
        @items = response.first(30)
    end
    
    def mini
        response = RakutenWebService::Ichiba::Item.search(keyword: "スカート ミニ", imageFlag: 1)
        @items = response.first(30)
    end
    
    def jeans
        response = RakutenWebService::Ichiba::Item.search(keyword: "ジーンズ", imageFlag: 1)
        @items = response.first(30)
    end

    def dress
        response = RakutenWebService::Ichiba::Item.search(keyword: "ワンピース", imageFlag: 1)
        @items = response.first(30)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_btn.html.erb
<div class="search">
    <div class="btn-group">
      <button type="button" class="btn btn-danger btn-lg dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        スカート <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "ロング", long_path %></li>
        <li><%= link_to "ミニ", mini_path %></li>
      </ul>
    </div>
</div>

<div class="search">
    <%= button_to "ジーンズ", jeans_path, method: :get, class: "btn btn-primary btn-lg" %>
</div>
<div class="search">
    <%= button_to "ワンピース", dress_path, method: :get, class: "btn btn-success btn-lg" %>
</div>

app/views/items/_item.html.erb
<% if @items.present? %>
    <% @items.each do |item| %>
        <%= link_to image_tag(item['mediumImageUrls'].first['imageUrl'], class: "img-thumbnail", border: '0'), item['itemUrl'], target: "_blank" %>
    <% end %>
<% end %>

app/views/items/dress.html.erb
<%= render 'btn' %>

<%= render 'item' %>

app/views/items/jeans.html.erb
<%= render 'btn' %>

<%= render 'item' %>

app/views/items/long.html.erb
<%= render 'btn' %>

<%= render 'item' %>

app/views/items/mini.html.erb
<%= render 'btn' %>

<%= render 'item' %>

app/views/items/show.html.erb
<%= render 'btn' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Skirt</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>